export const CORE_COMBINATION_SNAPSHOT_LIMIT_V1 = 3;
export const CORE_COMBINATION_SNAPSHOT_MAX_SLOTS_V1 = 2;
export const CANARY_CORE_COMPLETION_SCORE_GAP_V1 = 15;
export const CANARY_CORE_COMPLETION_MAX_DISTANCE_METERS_V1 = 1000;
